version: '3'

services:
    ubuntu:
        build:
            context: ./ubuntu
            args:
                - USER=$USER
                - USER_ID=1000
                - GROUP_ID=1000
        image: mauro/ubuntu

    php72:
        build:
            context: ./php/php72
            args:
                - USER=$USER
                - USER_ID=1000
                - GROUP_ID=1000
        image: mauro/php:72

    php73:
        build:
            context: ./php/php73
            args:
                - USER=$USER
                - USER_ID=1000
                - GROUP_ID=1000
        image: mauro/php:73
    
    php74:
        build:
            context: ./php/php74
            args:
                - USER=$USER
                - USER_ID=1000
                - GROUP_ID=1000
        image: mauro/php:74
    
    php8:
        build:
            context: ./php/php8
            args:
                - USER=$USER
                - USER_ID=1000
                - GROUP_ID=1000
        image: mauro/php:8
    
    node:
        build:
            context: ./node
            args:
                - USER=$USER
        image: mauro/node
        depends_on: 
            - ubuntu
    
    deno:
        build:
            context: ./deno
            args:
                - USER=$USER
        image: mauro/deno
        depends_on: 
            - ubuntu
    
    conda:
        build:
            context: ./python/conda
            args:
                - USER=$USER
        image: mauro/conda
        depends_on: 
            - ubuntu

    pydata:
        build:
            context: ./python/pydata
            args:
                - USER=$USER
        image: mauro/pydata
        depends_on: 
            - ubuntu