version: '3'

services:
    ubuntu:
        build:
            context: ./ubuntu
            args:
                - USER=$USER
                - USER_ID=1000
                - GROUP_ID=1000
        image: mauro/ubuntu

    laravel72:
        build:
            context: ./laravel/php72
            args:
                - USER=$USER
                - USER_ID=1000
                - GROUP_ID=1000
        image: mauro/laravel:php72

    laravel73:
        build:
            context: ./laravel/php73
            args:
                - USER=$USER
                - USER_ID=1000
                - GROUP_ID=1000
        image: mauro/laravel:php73
    
    laravel74:
        build:
            context: ./laravel/php74
            args:
                - USER=$USER
                - USER_ID=1000
                - GROUP_ID=1000
        image: mauro/laravel:php74
    
    node:
        build:
            context: ./node
            args:
                - USER=$USER
        image: mauro/node
        depends_on: 
            - ubuntu
    
    deno:
        build:
            context: ./deno
            args:
                - USER=$USER
        image: mauro/deno
        depends_on: 
            - ubuntu
    
    conda:
        build:
            context: ./python/conda
            args:
                - USER=$USER
        image: mauro/conda
        depends_on: 
            - ubuntu

    pydata:
        build:
            context: ./python/pydata
            args:
                - USER=$USER
        image: mauro/pydata
        depends_on: 
            - ubuntu
    pyds:
        build:
            context: ./pyds
        image: mauro/pyds
        depends_on: 
            - ubuntu