version: '3'

services:
    ubuntu:
        build:
            context: ./ubuntu
            args:
                - USER=$USER
                - USER_ID=1000
                - GROUP_ID=1000
                - SSHPRI=$SSHPRI
                - SSHPUB=$SSHPUB
                - GITGLO=$GITGLO
        image: mauro/ubuntu

    laravel:
        build:
            context: ./laravel
            args:
                - USER=$USER
                - USER_ID=1000
                - GROUP_ID=1000
                - SSHPRI=$SSHPRI
                - SSHPUB=$SSHPUB
                - GITGLO=$GITGLO
        image: mauro/laravel
    
    node:
        build:
            context: ./node
            args:
                - USER=$USER
        image: mauro/node
        depends_on: 
            - ubuntu
    
    deno:
        build:
            context: ./deno
            args:
                - USER=$USER
        image: mauro/deno
        depends_on: 
            - ubuntu
    
    conda:
        build:
            context: ./python/conda
            args:
                - USER=$USER
        image: mauro/conda
        depends_on: 
            - ubuntu

    pydata:
        build:
            context: ./python/pydata
            args:
                - USER=$USER
        image: mauro/pydata
        depends_on: 
            - ubuntu